# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/goalnest
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl-auto
spring.jpa.hibernate.ddl-auto=update

# Thymeleaf Cache (disable for dev)
spring.thymeleaf.cache=false
